### ISSUE TITLE
代码迁移到github

### ISSUE THREAD

**Issue by bruno-latour** [yottachain/YTFS#21]
初始化代码仓库，将本地代码阶段性版本上传

**Comment by bruno-latour** [comment]
分功能代码仓库的建立，列表见4.16 邮件 与 github.com/yottachain/YTFS/YTFS Config/代码仓库列表.xsl

**Comment by bruno-latour** [comment]
截止昨天为止，已经完成。

**Comment by babyNEKO** [comment]
这到底什么情况
项目废了？
